import Head from 'next/head'
import styles from './AppHeader.module.css'

const AppHeader = () => {
  return (
    <>
      <Head>
        <title>TMDB Next</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.appHeader}>
        <h1>The Movie Database</h1>
        <p>As a Next application</p>
      </header>
    </>
  )
}

export default AppHeader
